'''ADICIONE AO MÓDULO MOEDA.PY CRIADO NOS DESAFIOS ANTERIORES, UMA FUNÇÃO CHAMADA RESUMO(), QUE MOSTRE
NA TELA ALGUMAS INFORMAÇÕES GERADAS PELAS FUNÇÕES QUE JÁ TEMOS NO MÓDULO CRIADO ATÉ AQUI'''
from ex110 import moeda

p = float(input('Digite o preço: R$'))
moeda.resumo(p, 20, 30)