'''DENTRO DO PACOTE UTILIDADESCEV QUE CRIAMOS NO DESAFIO 111, TEMOS UM MÓDULO CHAMADO DADO.
CRIE UMA FUNÇÃO CHAMADA LEIADINHEIRO() QUE SEJA CAPAZ DE FUNCIONAR COMO UMA FUNÇÃO INPUT(),
MAS COM UMA VALIDAÇÃO DE DADOS PARA ACEITAR APENAS VALORES QUE SEJAM MONETÁRIOS.'''
from ex112.utilidadesCeV import moeda, dado

p = dado.leiaDinheiro('Digite o preço: R$')
moeda.resumo(p, 20, 30)

