'''CRIE UM PACOTE CHAMADO UTILIDADESCEV QUE TENHA DOIS MÓDULOS INTERNOS CHAMADOS MOEDAS E DADO.
TRANFIRA TODAS AS FUNÇÕES UTILIZADAS NOS DESAFIOS 107 A 110 PARA O PRIMEIRO PACOTE E MANTENHA TUDO FUNCIONANDO'''
from ex111.utilidadesCeV import moeda

p = float(input('Digite o preço: R$'))
moeda.resumo(p, 20, 30)
